import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-white/10 px-6">
          <nav className="flex space-x-6">
            <a href="/">Home</a>
            <a href="/announcements">News</a>
            <a href="/results">Results</a>
            <a href="/photos">Photos</a>
            <a href="/archive">Previous Years</a>
            <a href="/sponsors">Sponsors</a>
            <a href="/volunteers">Volunteers</a>
            <a href="/studio">Sanity</a>
          </nav>
        </header>
        {children}
        </body>
    </html>
  );
}
